### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by siberianguy** [MihaMarkic/Cake.Putty#5]
Will this plugin work on Mac if Putty's port is installed? Or is it specific to Windows? I'm looking for a way to deploy a .NET Core project to Raspberry PI and I found an article (https://jeremylindsayni.wordpress.com/2017/07/23/running-a-net-core-2-app-on-raspbian-jessie-and-deploying-to-the-pi-with-cake/) that uses your plugin. Not sure how it can be done on Mac.

**Comment by MihaMarkic** [comment]
Hi there,
Right, I haven't tested it on Mac or Linux. I assume you have it on the Mac? Theoretically I have to recompile it for .net core and use proper putty's name on Mac. Will check.

**Comment by siberianguy** [comment]
Hey! Thanks for your feedback. I feel like what you mentioned should work. In the comments of the blog post mentioned above there're people who solved a problem with finding Putty by specifying a custom path to it. But as I understand the current implementation depends on putty.exe and the "exe" part is problematic.

What might be a better solution though is to use a native ssh tool for Mac instead of Putty's port.

**Comment by MihaMarkic** [comment]
Starting with 1.2.0 it should properly support putty on MacOS and probably Linux as well. Reopen or create a new issue if there are still problems.

**Comment by siberianguy** [comment]
Tested it. It works! Thanks a lot :)
