### ISSUE TITLE
Pscp: Could not locate executable.

### ISSUE THREAD

**Issue by BLipscomb** [MihaMarkic/Cake.Putty#6]
I'm using version 1.3.0, and when I run Pscp in my Cake script I get the following error in Powershell.

Pscp: Could not locate executable.

Any ideas on how to fix?

**Comment by MihaMarkic** [comment]
Check the requirements:
"Tested only on Windows at this time. Ensure that Putty command line tools (pspc, plink) can be located using the PATH (e.g. check that it can be found with which pscp).'
Is this the case for you?

**Comment by BLipscomb** [comment]
I think I was confused. I thought the pscp.exe would come with Cake.Putty, but I'm assuming I need to download it separately. That could be my issue.

**Comment by MihaMarkic** [comment]
Most probably. Addin is just a bridge that allows you to invoke Putty from Cake.

**Comment by BLipscomb** [comment]
Okay thanks. I can close the issue if you'd like. Or if you'd like I can add a comment about downloading those exe files in the md file.

**Comment by MihaMarkic** [comment]
Yeah, let's close it and if you still have problems reopen it.
